/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author niharika
 */
package Connect;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class vinfo extends javax.swing.JFrame {

    private static String dID;
    Connection con = null;
    Statement	st = null;
    ResultSet	rs = null;
    /**
     * Creates new form vinfo
     */
    public vinfo() {
    }
    
    public vinfo(String did)	{
	vinfo.dID = did;
	initComponents();
	con=Connect.ConnectDB();
	Update();
    }
    
    public void Update()
    {
	try {
	    String rq="select * from viruses where VirusID=(select VirusID from diseases where DiseaseID = '"+vinfo.dID+"')";
	    System.out.println("Query for Virus Details: '"+rq+"'");
	    st = con.createStatement();
	    rs = st.executeQuery(rq);
	    while(rs.next()) {
		txtVid.setText(rs.getString(1));
		txtVname.setText(rs.getString(2));
		txtVfamily.setText(rs.getString(4));
		txtVector.setText(rs.getString(5));
		txtVsize.setText(rs.getString(6)+" nm");
		txtOrgans.setText(rs.getString(3));
	    }

//	    txtDname.setText(this.getDisease());
	    
//	    rs_dur = st.executeQuery(rq_dur);
//	    while(rs_dur.next())
//		txtDduration.setText(rs_dur.getString(1));
	} catch (SQLException ex) {
	    Logger.getLogger(ShowDis.class.getName()).log(Level.SEVERE, null, ex);
	}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFamily = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblVector = new javax.swing.JLabel();
        lblSize1 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtVfamily = new javax.swing.JTextField();
        txtVector = new javax.swing.JTextField();
        txtOrgans = new javax.swing.JTextField();
        txtVname = new javax.swing.JTextField();
        txtVsize = new javax.swing.JTextField();
        txtVid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        lblFamily.setBackground(new java.awt.Color(204, 255, 204));
        lblFamily.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblFamily.setForeground(new java.awt.Color(0, 51, 51));
        lblFamily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFamily.setText("Virus Family");
        lblFamily.setOpaque(true);

        lblName.setBackground(new java.awt.Color(204, 255, 204));
        lblName.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 51));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Virus Name");
        lblName.setOpaque(true);

        lblSize.setBackground(new java.awt.Color(204, 255, 204));
        lblSize.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblSize.setForeground(new java.awt.Color(0, 51, 51));
        lblSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSize.setText("Size of Virus");
        lblSize.setOpaque(true);

        lblVector.setBackground(new java.awt.Color(204, 255, 204));
        lblVector.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblVector.setForeground(new java.awt.Color(0, 51, 51));
        lblVector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVector.setText("Vector");
        lblVector.setOpaque(true);

        lblSize1.setBackground(new java.awt.Color(204, 255, 204));
        lblSize1.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblSize1.setForeground(new java.awt.Color(0, 51, 51));
        lblSize1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSize1.setText("Organs Affected");
        lblSize1.setOpaque(true);

        lblID.setBackground(new java.awt.Color(204, 255, 204));
        lblID.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 51, 51));
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblID.setText("Virus ID");
        lblID.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFamily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSize1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
            .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVector, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        txtVfamily.setBackground(new java.awt.Color(0, 51, 51));
        txtVfamily.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        txtVfamily.setForeground(new java.awt.Color(204, 255, 204));
        txtVfamily.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtVector.setBackground(new java.awt.Color(0, 51, 51));
        txtVector.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        txtVector.setForeground(new java.awt.Color(204, 255, 204));
        txtVector.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtOrgans.setBackground(new java.awt.Color(0, 51, 51));
        txtOrgans.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        txtOrgans.setForeground(new java.awt.Color(204, 255, 204));
        txtOrgans.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtVname.setBackground(new java.awt.Color(0, 51, 51));
        txtVname.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        txtVname.setForeground(new java.awt.Color(204, 255, 204));
        txtVname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtVsize.setBackground(new java.awt.Color(0, 51, 51));
        txtVsize.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        txtVsize.setForeground(new java.awt.Color(204, 255, 204));
        txtVsize.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtVid.setBackground(new java.awt.Color(0, 51, 51));
        txtVid.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        txtVid.setForeground(new java.awt.Color(204, 255, 204));
        txtVid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVfamily)
            .addComponent(txtOrgans)
            .addComponent(txtVector)
            .addComponent(txtVname, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtVsize)
            .addComponent(txtVid)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtVid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtVfamily, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVector, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txtVsize, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOrgans, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("K N O W  Y O U R  V I R U S");
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(205, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLICK HERE TO GO BACK!");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
	this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(vinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(vinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(vinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(vinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new vinfo().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFamily;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSize1;
    private javax.swing.JLabel lblVector;
    private javax.swing.JTextField txtOrgans;
    private javax.swing.JTextField txtVector;
    private javax.swing.JTextField txtVfamily;
    private javax.swing.JTextField txtVid;
    private javax.swing.JTextField txtVname;
    private javax.swing.JTextField txtVsize;
    // End of variables declaration//GEN-END:variables
}
